title: Amy Wang # your name (or website title) here
logo: "images/k.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  A data-driven storyteller,
  <br>
  a rock 'n roll lover,
  <br>
  a learner
  
  
  
theme: jekyll-theme-minimal
show_downloads: false
